import { orderStudyTypes } from './schemas/studyCatalog'

type StudyType = (typeof orderStudyTypes)[number]
type Props = { type: StudyType; details: Record<string, unknown> }

const studyLabels: Record<StudyType, string> = { radiography: 'Radiografía', radiography_2d: 'Radiografía 2D', cbct: 'Tomografía CBCT', cephalometric_analysis: 'Análisis cefalométrico', study_models: 'Modelos de estudio', intraoral_scan: 'Escaneo intraoral', orthodontic_package: 'Paquete ortodóncico', aligner_package: 'Paquete de alineadores', laboratory_order: 'Orden de laboratorio', endodontic_evaluation: 'Evaluación endodóntica' }
const labels: Record<string, string> = { radiographyType: 'Tipo de radiografía', region: 'Región', clinicalIndication: 'Indicación clínica', notes: 'Notas', variant: 'Proyección', side: 'Lado', scope: 'Alcance', mouthPosition: 'Posición de boca', projection: 'Proyección', fov: 'Campo de visión (FOV)', toothNumbers: 'Piezas dentales', amperage: 'Amperaje', tmjPosition: 'Posición ATM', regionOfInterestNotes: 'Notas de región de interés', analyses: 'Análisis', customTechnique: 'Técnica personalizada', material: 'Material', outputFormat: 'Formato de entrega', package: 'Paquete', lateralScope: 'Alcance lateral', cephalometricTechnique: 'Técnica cefalométrica', modelMaterial: 'Material de modelos', cbct: 'CBCT', tomography: 'Tomografía', lateral: 'Lateral', intraoralScanStl: 'Escaneo intraoral STL', cephalometry: 'Cefalometría', models: 'Modelos', panoramic: 'Panorámica', clinicalPhotography: 'Fotografía clínica', tomographyFov: 'FOV de tomografía', work: 'Trabajo solicitado', receivedAt: 'Fecha de recepción', deliveryAt: 'Fecha de entrega', impression: 'Impresión', antagonist: 'Antagonista', biteRegistration: 'Registro de mordida', prototype: 'Prototipo', photos: 'Fotografías', other: 'Otro', materialVariant: 'Variante', shade: 'Tono', system: 'Sistema', substrate: 'Sustrato', final: 'Tono final', colorimeter: 'Colorímetro', implant: 'Implante', brand: 'Marca', diameter: 'Diámetro', attachments: 'Aditamentos', name: 'Nombre', quantity: 'Cantidad', customized: 'Personalizado', bar: 'Barra', toothNumber: 'Pieza dental', canals: 'Conductos', canal: 'Conducto', characteristics: 'Características', tentativeLength: 'Longitud tentativa', workingLength: 'Longitud de trabajo', guttaPerchaPoint: 'Punta de gutapercha', anatomicalCrown: 'Corona anatómica', inflammation: 'Inflamación', gingivitis: 'Gingivitis', calculus: 'Cálculo', fistula: 'Fístula', fistulaLocation: 'Ubicación de fístula', pain: 'Dolor', percussion: 'Percusión', palpation: 'Palpación', periodontalPockets: 'Bolsas periodontales', probing: 'Sondaje', mobility: 'Movilidad', pulpChamber: 'Cámara pulpar', radiographicLesions: 'Lesiones radiográficas', rootFracture: 'Fractura radicular', calcification: 'Calcificación', resorption: 'Reabsorción', periodontalLigament: 'Ligamento periodontal', pulpalDiagnosis: 'Diagnóstico pulpar', periapicalDiagnosis: 'Diagnóstico periapical', treatmentPlan: 'Plan de tratamiento', instrumentationTechnique: 'Técnica de instrumentación', obturationTechnique: 'Técnica de obturación', irrigatingAgent: 'Agente irrigante', postEndodonticRestoration: 'Restauración postendodóntica' }
const values: Record<string, string> = { left: 'Izquierdo', right: 'Derecho', complete: 'Completo', profile_only: 'Solo perfil', open: 'Abierta', closed: 'Cerrada', teeth: 'Dientes', maxilla: 'Maxilar', mandible: 'Mandíbula', maxilla_mandible: 'Maxilar y mandíbula', tmj: 'ATM', airways: 'Vías aéreas', paranasal_sinuses: 'Senos paranasales', facial_skeleton: 'Esqueleto facial', normal: 'Normal', high: 'Alta', occlusion: 'Oclusión', opening: 'Apertura', both: 'Ambas', orthodontic_plaster: 'Yeso ortodóncico', resin: 'Resina', complete_3d: 'Completo 3D', panoramic_insight: 'Panorámica Insight', panoramic: 'Panorámica', half_panoramic: 'Media panorámica', lateral_cephalometric: 'Cefalométrica lateral', tmj_open_closed_lateral: 'ATM lateral abierta/cerrada', caldwell_hirtz: 'Caldwell-Hirtz', waters: 'Waters', pa_ap: 'PA/AP', carpal: 'Carpal', steiner: 'Steiner', jarabak: 'Jarabak', ricketts: 'Ricketts', ricketts_summary: 'Resumen Ricketts', custom: 'Personalizado', analog: 'Análoga', digital: 'Digital', upper: 'Superior', lower: 'Inferior', vita: 'Vita', chromascop: 'Chromascop', emax: 'E.max', zirconia: 'Zirconia', feldspathic: 'Feldespática', wax_up: 'Wax-up', pmma: 'PMMA', splint: 'Férula', surgical_guide: 'Guía quirúrgica', periodontal_surgical_guide: 'Guía quirúrgica periodontal', mono: 'Monolítico', estra: 'Estratificado' }

function present(value: unknown) { return value !== '' && value !== undefined && value !== null && (!Array.isArray(value) || value.length > 0) }
function display(value: unknown): string { if (typeof value === 'string') return values[value] ?? value; if (typeof value === 'boolean') return value ? 'Sí' : 'No'; if (typeof value === 'number') return String(value); return '—' }

function Fields({ value }: { value: Record<string, unknown> }) {
  return <dl className="grid gap-x-5 gap-y-2 sm:grid-cols-2">{Object.entries(value).filter(([, item]) => present(item)).map(([key, item]) => {
    if (Array.isArray(item) && item.every((entry) => typeof entry !== 'object' || entry === null)) return <div key={key}><dt className="text-xs font-medium text-muted-foreground">{labels[key] ?? key}</dt><dd>{item.map(display).join(', ')}</dd></div>
    if (Array.isArray(item)) return <div key={key} className="sm:col-span-2"><dt className="mb-1 text-xs font-medium text-muted-foreground">{labels[key] ?? key}</dt><dd className="space-y-2">{item.map((entry, index) => <div key={index} className="rounded-md bg-muted/50 p-3"><p className="mb-2 text-xs font-medium text-muted-foreground">Elemento {index + 1}</p><Fields value={entry as Record<string, unknown>} /></div>)}</dd></div>
    if (item && typeof item === 'object') return <div key={key} className="sm:col-span-2"><dt className="mb-1 text-xs font-medium text-muted-foreground">{labels[key] ?? key}</dt><dd className="rounded-md bg-muted/50 p-3"><Fields value={item as Record<string, unknown>} /></dd></div>
    return <div key={key}><dt className="text-xs font-medium text-muted-foreground">{labels[key] ?? key}</dt><dd>{display(item)}</dd></div>
  })}</dl>
}

export function StudyDetailsSummary({ type, details }: Props) {
  return <section className="space-y-3 text-sm"><div><p className="text-xs font-medium text-muted-foreground">Estudio</p><p className="font-medium">{studyLabels[type]}</p></div><Fields value={details} /></section>
}
