'use client'

import { useEffect, useState } from 'react'
import { createMemberAction, listMembersAction, updateMemberAction } from '#/modules/member/server/member'
import { listClinicsAction } from '#/modules/clinic/server/clinic'
import { Button } from '#/shared/components/ui/button'

type Members = Awaited<ReturnType<typeof listMembersAction>>
type Clinics = Awaited<ReturnType<typeof listClinicsAction>>

export default function MembersPage() {
  const [members, setMembers] = useState<Members>([]); const [clinics, setClinics] = useState<Clinics>([]); const [error, setError] = useState(''); const [role, setRole] = useState<'owner' | 'assistant'>('assistant'); const [clinicId, setClinicId] = useState('')
  const load = async () => { const [nextMembers, nextClinics] = await Promise.all([listMembersAction(), listClinicsAction()]); setMembers(nextMembers); setClinics(nextClinics) }
  useEffect(() => { void load().catch(() => setError('No se pudieron cargar los miembros.')) }, [])
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { await createMemberAction({ name: form.get('name'), email: form.get('email'), password: form.get('password'), role, clinicId: role === 'assistant' ? clinicId : undefined }); event.currentTarget.reset(); setClinicId(''); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo crear el miembro.') } }
  async function change(member: Members[number], nextRole: 'owner' | 'assistant', nextClinicId: string, active = member.active) { try { await updateMemberAction({ memberId: member.id, role: nextRole, clinicId: nextRole === 'assistant' ? nextClinicId : null, active }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo actualizar el miembro.') } }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Miembros</h1><p className="text-muted-foreground">Crea accesos directos; no se envían invitaciones por correo.</p></div><form onSubmit={create} className="grid gap-3 rounded-lg border p-4 md:grid-cols-2"><input name="name" className="rounded border p-2" placeholder="Nombre" required /><input name="email" className="rounded border p-2" type="email" placeholder="Correo" required /><input name="password" className="rounded border p-2" type="password" minLength={8} placeholder="Contraseña inicial" required /><select className="rounded border p-2" value={role} onChange={(e) => setRole(e.target.value as 'owner' | 'assistant')}><option value="assistant">Assistant</option><option value="owner">Owner</option></select>{role === 'assistant' && <select className="rounded border p-2" value={clinicId} onChange={(e) => setClinicId(e.target.value)} required><option value="">Clínica asignada</option>{clinics.map((clinic) => <option value={clinic.id} key={clinic.id}>{clinic.name}</option>)}</select>}<Button type="submit">Crear miembro</Button></form>{error && <p className="text-sm text-destructive">{error}</p>}<div className="space-y-3">{members.map((item) => <article key={item.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><div className="min-w-48 flex-1"><p className="font-medium">{item.name}</p><p className="text-sm text-muted-foreground">{item.email} · {item.active ? 'Activo' : 'Desactivado'}</p></div><select value={item.role} onChange={(e) => void change(item, e.target.value as 'owner' | 'assistant', item.assignedClinicId ?? '')}><option value="owner">Owner</option><option value="assistant">Assistant</option></select>{item.role === 'assistant' && <select value={item.assignedClinicId ?? ''} onChange={(e) => void change(item, 'assistant', e.target.value)}><option value="">Clínica</option>{clinics.map((clinic) => <option value={clinic.id} key={clinic.id}>{clinic.name}</option>)}</select>}<Button variant="outline" onClick={() => void change(item, item.role as 'owner' | 'assistant', item.assignedClinicId ?? '', !item.active)}>{item.active ? 'Desactivar' : 'Activar'}</Button></article>)}</div></div>
}
