CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint
CREATE TYPE "calendar_resource_type" AS ENUM('dentist', 'equipment', 'room', 'chair', 'other');--> statement-breakpoint
CREATE TYPE "calendar_resource_status" AS ENUM('active', 'inactive');--> statement-breakpoint
CREATE TYPE "appointment_kind" AS ENUM('clinical', 'study');--> statement-breakpoint
CREATE TYPE "appointment_source" AS ENUM('internal', 'whatsapp', 'public_order');--> statement-breakpoint
CREATE TYPE "appointment_status" AS ENUM('requested', 'scheduled', 'checked_in', 'in_progress', 'completed', 'cancelled', 'rejected', 'no_show');--> statement-breakpoint
CREATE TYPE "appointment_event_type" AS ENUM('created', 'requested', 'scheduled', 'rescheduled', 'checked_in', 'started', 'completed', 'cancelled', 'rejected', 'no_show');--> statement-breakpoint
ALTER TABLE "clinic" ADD COLUMN "slot_interval_minutes" integer DEFAULT 15 NOT NULL;--> statement-breakpoint
CREATE TABLE "calendar_resource" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" text NOT NULL REFERENCES "organization"("id") ON DELETE cascade, "clinic_id" uuid NOT NULL REFERENCES "clinic"("id") ON DELETE cascade, "type" "calendar_resource_type" NOT NULL, "member_id" text REFERENCES "member"("id") ON DELETE set null, "name" text NOT NULL, "status" "calendar_resource_status" DEFAULT 'active' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE "resource_availability" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "resource_id" uuid NOT NULL REFERENCES "calendar_resource"("id") ON DELETE cascade, "day_of_week" integer NOT NULL CHECK ("day_of_week" BETWEEN 0 AND 6), "start_time" text NOT NULL, "end_time" text NOT NULL, CHECK ("start_time" < "end_time"));--> statement-breakpoint
CREATE TABLE "resource_block" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "resource_id" uuid NOT NULL REFERENCES "calendar_resource"("id") ON DELETE cascade, "starts_at" timestamp with time zone NOT NULL, "ends_at" timestamp with time zone NOT NULL, "reason" text, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CHECK ("starts_at" < "ends_at"));--> statement-breakpoint
CREATE TABLE "appointment" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" text NOT NULL REFERENCES "organization"("id") ON DELETE cascade, "clinic_id" uuid NOT NULL REFERENCES "clinic"("id") ON DELETE cascade, "patient_id" uuid NOT NULL REFERENCES "patient"("id"), "order_id" uuid REFERENCES "order"("id"), "kind" "appointment_kind" NOT NULL, "source" "appointment_source" DEFAULT 'internal' NOT NULL, "status" "appointment_status" DEFAULT 'requested' NOT NULL, "starts_at" timestamp with time zone NOT NULL, "ends_at" timestamp with time zone NOT NULL, "notes" text, "created_by_user_id" text REFERENCES "user"("id") ON DELETE set null, "cancelled_at" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CHECK ("starts_at" < "ends_at"));--> statement-breakpoint
CREATE UNIQUE INDEX "appointment_order_unique" ON "appointment" ("order_id") WHERE "order_id" IS NOT NULL AND "status" NOT IN ('completed', 'cancelled', 'rejected', 'no_show');--> statement-breakpoint
CREATE TABLE "appointment_reservation" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "appointment_id" uuid NOT NULL REFERENCES "appointment"("id") ON DELETE cascade, "resource_id" uuid NOT NULL REFERENCES "calendar_resource"("id") ON DELETE cascade, "starts_at" timestamp with time zone NOT NULL, "ends_at" timestamp with time zone NOT NULL, "active" boolean DEFAULT true NOT NULL, CHECK ("starts_at" < "ends_at"));--> statement-breakpoint
ALTER TABLE "appointment_reservation" ADD CONSTRAINT "appointment_reservation_no_overlap" EXCLUDE USING gist ("resource_id" WITH =, tstzrange("starts_at", "ends_at", '[)') WITH &&) WHERE ("active");--> statement-breakpoint
CREATE TABLE "appointment_event" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "appointment_id" uuid NOT NULL REFERENCES "appointment"("id") ON DELETE cascade, "type" "appointment_event_type" NOT NULL, "user_id" text REFERENCES "user"("id") ON DELETE set null, "metadata" jsonb DEFAULT '{}' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE INDEX "calendar_resource_organization_clinic_idx" ON "calendar_resource" ("organization_id", "clinic_id");--> statement-breakpoint
CREATE INDEX "calendar_resource_member_idx" ON "calendar_resource" ("member_id");--> statement-breakpoint
CREATE INDEX "resource_availability_resource_day_idx" ON "resource_availability" ("resource_id", "day_of_week");--> statement-breakpoint
CREATE INDEX "resource_block_resource_time_idx" ON "resource_block" ("resource_id", "starts_at", "ends_at");--> statement-breakpoint
CREATE INDEX "appointment_organization_clinic_time_idx" ON "appointment" ("organization_id", "clinic_id", "starts_at");--> statement-breakpoint
CREATE INDEX "appointment_patient_time_idx" ON "appointment" ("patient_id", "starts_at");--> statement-breakpoint
CREATE INDEX "appointment_order_idx" ON "appointment" ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "appointment_reservation_appointment_resource_unique" ON "appointment_reservation" ("appointment_id", "resource_id");--> statement-breakpoint
CREATE INDEX "appointment_reservation_resource_time_idx" ON "appointment_reservation" ("resource_id", "starts_at", "ends_at");--> statement-breakpoint
CREATE INDEX "appointment_event_appointment_idx" ON "appointment_event" ("appointment_id");
