'use client'
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useState } from 'react'
import { createAuthenticatedPublicAppointmentAction, createAuthenticatedPublicStudyOrderAction, createExistingPublicAppointmentAction, createExistingPublicStudyOrderAction, createPublicAppointmentAction, createPublicStudyOrderAction, getAuthenticatedPatientBookingAction, getPublicAvailabilityAction, listPublicBookingClinicsAction } from '#/modules/appointment/server/publicAppointment'
import { Button } from '#/shared/components/ui/button'
import { Input } from '#/shared/components/ui/input'
import { Label } from '#/shared/components/ui/label'
import { NativeSelect } from '#/shared/components/ui/native-select'
import { Textarea } from '#/shared/components/ui/textarea'
import AppointmentWizardFrame from './AppointmentWizardFrame'

type Clinic = { publicSlug: string; name: string; addressLine: string | null; phone: string | null }
type Slot = { startsAt: Date; endsAt: Date }
type Account = { patientId: string; firstName: string; paternalLastName: string | null; maternalLastName: string | null; phone: string | null; email: string | null }
type Props = { onBack: () => void; mode: 'general' | 'study' }
type IdentityChoice = 'existing' | 'new' | null

export default function PatientAppointmentWizard({ onBack, mode }: Props) {
  const [clinics, setClinics] = useState<Clinic[]>([]); const [clinicPublicSlug, setClinicPublicSlug] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [slots, setSlots] = useState<Slot[]>([]); const [startsAt, setStartsAt] = useState('')
  const [account, setAccount] = useState<Account | null | undefined>(undefined); const [identityChoice, setIdentityChoice] = useState<IdentityChoice>(null)
  const [firstName, setFirstName] = useState(''); const [paternalLastName, setPaternalLastName] = useState(''); const [maternalLastName, setMaternalLastName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState('')
  const [studyType, setStudyType] = useState<'radiography' | 'cbct'>('radiography'); const [details, setDetails] = useState({ radiographyType: '', region: '', anatomicalRegion: '', specificArea: '', clinicalIndication: '', notes: '' }); const [hasReferrer, setHasReferrer] = useState(false); const [doctor, setDoctor] = useState({ firstName: '', paternalLastName: '', email: '', phone: '' })
  const [step, setStep] = useState(1); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const successMessage = mode === 'study' ? 'Tu estudio quedó programado. Te esperamos.' : 'Tu cita quedó programada. Te esperamos.'
  const authenticated = !!account
  const isExisting = identityChoice === 'existing'
  const lastStep = mode === 'study' ? (authenticated ? 4 : 6) : (authenticated ? 2 : 4)
  const stepNames = mode === 'study' ? (authenticated ? ['Disponibilidad', 'Tipo de estudio', 'Detalles del estudio', 'Revisión', 'Confirmación'] : ['Disponibilidad', 'Identificación', 'Tus datos', 'Tipo de estudio', 'Detalles del estudio', 'Revisión', 'Confirmación']) : (authenticated ? ['Disponibilidad', 'Revisión', 'Confirmación'] : ['Disponibilidad', 'Identificación', 'Tus datos', 'Revisión', 'Confirmación'])

  useEffect(() => { void getAuthenticatedPatientBookingAction().then(setAccount).catch(() => setAccount(null)) }, [])
  useEffect(() => { void listPublicBookingClinicsAction().then((items) => { setClinics(items); setClinicPublicSlug(items[0]?.publicSlug ?? '') }).catch(() => setMessage('No podemos mostrar las clínicas por ahora.')) }, [])
  useEffect(() => { if (!clinicPublicSlug || !date) return; setLoading(true); setStartsAt(''); void getPublicAvailabilityAction({ clinicPublicSlug, date }).then((result) => { setSlots(result.success ? result.slots : []); if (!result.success) setMessage('No hay horarios disponibles por ahora.') }).catch(() => { setSlots([]); setMessage('No podemos consultar horarios por ahora.') }).finally(() => setLoading(false)) }, [clinicPublicSlug, date])

  const field = (id: string, label: string, value: string, onChange: (value: string) => void, options: { type?: string; required?: boolean } = {}) => <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} className="h-10" type={options.type} value={value} onChange={(event) => onChange(event.target.value)} required={options.required} /></div>
  const contactFields = <div className="grid gap-4 sm:grid-cols-2">{field('patient-phone', 'Teléfono', phone, setPhone)}{field('patient-email', 'Correo', email, setEmail, { type: 'email' })}</div>
  const dataFields = <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{field('patient-first-name', 'Nombre', firstName, setFirstName, { required: true })}{field('patient-paternal-last-name', 'Apellido paterno', paternalLastName, setPaternalLastName)}</div>{field('patient-maternal-last-name', 'Apellido materno', maternalLastName, setMaternalLastName)}{contactFields}<p className="text-xs text-muted-foreground">Ingresa al menos un teléfono o correo.</p></div>
  const availability = <div className="space-y-4"><div className="space-y-2"><Label htmlFor="clinic">Clínica</Label><NativeSelect id="clinic" className="w-full" value={clinicPublicSlug} onChange={(event) => setClinicPublicSlug(event.target.value)} required>{clinics.map((clinic) => <option key={clinic.publicSlug} value={clinic.publicSlug}>{clinic.name}</option>)}</NativeSelect></div><div className="space-y-2"><Label htmlFor="date">Fecha</Label><Input id="date" type="date" value={date} min={new Date().toISOString().slice(0, 10)} onChange={(event) => setDate(event.target.value)} required /></div><fieldset className="space-y-2"><legend className="text-sm font-medium">Horarios disponibles</legend><div className="flex flex-wrap gap-2">{loading ? 'Consultando...' : slots.length ? slots.map((slot) => { const value = new Date(slot.startsAt).toISOString(); return <Button key={value} type="button" variant={startsAt === value ? 'default' : 'outline'} onClick={() => setStartsAt(value)}>{new Date(slot.startsAt).toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' })}</Button> }) : 'No hay horarios disponibles.'}</div></fieldset></div>
  const identity = account === undefined ? <p>Consultando tu cuenta...</p> : <div className="space-y-5"><h2 className="text-xl font-semibold">¿Ya sos paciente?</h2><div className="flex flex-wrap gap-3"><Button type="button" variant={isExisting ? 'default' : 'outline'} onClick={() => setIdentityChoice('existing')}>Ya soy paciente</Button><Button type="button" variant={identityChoice === 'new' ? 'default' : 'outline'} onClick={() => setIdentityChoice('new')}>Soy paciente nuevo</Button></div></div>
  const identityData = isExisting ? <div className="space-y-4"><p className="text-sm text-muted-foreground">Ingresa el correo o teléfono asociado con tus consultas previas.</p>{contactFields}</div> : dataFields
  const studyTypeContent = <fieldset className="space-y-3"><legend className="text-sm font-medium">Tipo de estudio</legend><Label><input type="radio" checked={studyType === 'radiography'} onChange={() => setStudyType('radiography')} /> Radiografía</Label><Label><input type="radio" checked={studyType === 'cbct'} onChange={() => setStudyType('cbct')} /> CBCT</Label></fieldset>
  const studyDetails = <div className="space-y-4">{studyType === 'radiography' ? <>{field('radiography-type', 'Tipo de radiografía', details.radiographyType, (value) => setDetails({ ...details, radiographyType: value }), { required: true })}{field('region', 'Pieza o región', details.region, (value) => setDetails({ ...details, region: value }), { required: true })}</> : <>{field('anatomical-region', 'Región anatómica', details.anatomicalRegion, (value) => setDetails({ ...details, anatomicalRegion: value }), { required: true })}{field('specific-area', 'Área específica', details.specificArea, (value) => setDetails({ ...details, specificArea: value }), { required: true })}</>}{field('clinical-indication', 'Indicación clínica', details.clinicalIndication, (value) => setDetails({ ...details, clinicalIndication: value }), { required: true })}<Textarea value={details.notes} onChange={(event) => setDetails({ ...details, notes: event.target.value })} placeholder="Notas" /><Label><input type="checkbox" checked={hasReferrer} onChange={(event) => setHasReferrer(event.target.checked)} /> Tengo profesional remitente</Label>{hasReferrer && <div className="grid gap-4 sm:grid-cols-2">{field('doctor-first-name', 'Nombre', doctor.firstName, (value) => setDoctor({ ...doctor, firstName: value }), { required: true })}{field('doctor-last-name', 'Apellido paterno', doctor.paternalLastName, (value) => setDoctor({ ...doctor, paternalLastName: value }), { required: true })}{field('doctor-email', 'Correo', doctor.email, (value) => setDoctor({ ...doctor, email: value }), { type: 'email', required: true })}</div>}</div>
  const review = <div className="space-y-3"><p className="text-sm text-muted-foreground">Revisa los datos antes de confirmar.</p><p><strong>Clínica y horario:</strong> {clinics.find((item) => item.publicSlug === clinicPublicSlug)?.name} · {date} {startsAt && new Date(startsAt).toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' })}</p><p><strong>Paciente:</strong> {authenticated ? 'Paciente de tu cuenta' : isExisting ? 'Paciente con consultas previas' : [firstName, paternalLastName, maternalLastName].filter(Boolean).join(' ')}</p>{mode === 'study' && <p><strong>Estudio:</strong> {studyType === 'radiography' ? 'Radiografía' : 'CBCT'}</p>}</div>
  const currentContent = step === 1 ? availability : !authenticated && step === 2 ? identity : !authenticated && step === 3 ? identityData : mode === 'general' ? (step === lastStep ? review : null) : (step === (authenticated ? 2 : 4) ? studyTypeContent : step === (authenticated ? 3 : 5) ? studyDetails : step === lastStep ? review : null)

  function validCurrentStep() { if (step === 1 && !startsAt) { setMessage('Selecciona un horario disponible.'); return false } if (!authenticated && step === 2 && !identityChoice) { setMessage('Elige una opción para continuar.'); return false } if (!authenticated && step === 3 && (!phone.replace(/\D/g, '') && !email)) { setMessage('Ingresa al menos un teléfono o correo.'); return false } return true }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!startsAt) return; setLoading(true); setMessage(''); const base = { clinicPublicSlug, startsAt: new Date(startsAt) }; const patient = { ...base, firstName, paternalLastName: paternalLastName || undefined, maternalLastName: maternalLastName || undefined, phone: phone || undefined, email: email || undefined }; const study = { ...patient, type: studyType, details: studyType === 'radiography' ? { radiographyType: details.radiographyType, region: details.region, clinicalIndication: details.clinicalIndication, notes: details.notes || undefined } : { anatomicalRegion: details.anatomicalRegion, specificArea: details.specificArea, clinicalIndication: details.clinicalIndication, notes: details.notes || undefined }, doctor: hasReferrer ? doctor : undefined } as const; const result = mode === 'study' ? authenticated ? await createAuthenticatedPublicStudyOrderAction({ ...base, ...study }) : isExisting ? await createExistingPublicStudyOrderAction(study) : await createPublicStudyOrderAction(study) : authenticated ? await createAuthenticatedPublicAppointmentAction(base) : isExisting ? await createExistingPublicAppointmentAction({ ...base, phone: phone || undefined, email: email || undefined }) : await createPublicAppointmentAction(patient); setLoading(false); if (result.success) { setMessage(successMessage); setStep(lastStep + 1) } else setMessage(result.error === 'SLOT_NOT_AVAILABLE' ? 'Ese horario ya no está disponible. Elige otro, por favor.' : 'No fue posible programar. Intenta más tarde.') }
  const next = (event: React.MouseEvent<HTMLButtonElement>) => { if (!event.currentTarget.form?.reportValidity() || !validCurrentStep()) return; setMessage(''); setStep((value) => value + 1) }
  const previous = () => { setMessage(''); setStep((value) => Math.max(1, value - 1)) }
  return <AppointmentWizardFrame title={mode === 'study' ? 'Agenda tu estudio' : 'Agenda tu cita'} subtitle="Selecciona una clínica y horario, completa los datos necesarios y confirma tu solicitud." steps={stepNames} currentStep={Math.min(step, stepNames.length)} backLabel="Elegir otra opción" onBack={step > 1 ? previous : onBack}><form className="space-y-5" onSubmit={submit}>{step > lastStep ? <p aria-live="polite">{successMessage}</p> : <>{currentContent}{message && <p aria-live="polite" className="text-sm">{message}</p>}<div className="flex justify-between border-t pt-5"><Button type="button" variant="outline" disabled={loading || step === 1} onClick={previous}>Anterior</Button>{step < lastStep ? <Button type="button" disabled={loading} onClick={next}>Siguiente</Button> : <Button type="submit" disabled={loading}>{loading ? 'Programando...' : mode === 'study' ? 'Confirmar estudio' : 'Confirmar cita'}</Button>}</div></>}</form></AppointmentWizardFrame>
}
