'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '#/shared/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/shared/components/ui/card'
import { Input } from '#/shared/components/ui/input'
import { Label } from '#/shared/components/ui/label'
import { NativeSelect } from '#/shared/components/ui/native-select'
import AppointmentWizardFrame from './AppointmentWizardFrame'
import { createProfessionalOrderAction, getProfessionalOrderAccessAction, getPublicClinicsAction } from '#/modules/order/server/generalOrder'
import { defaultStudyDetails, StudyDetailsForm } from '#/modules/order/StudyDetailsForm'
import { orderStudyTypes, studyDetailsSchemaByType } from '#/modules/order/schemas/studyCatalog'

type Clinic = { id: string; name: string; addressLine: string | null }
type StudyType = (typeof orderStudyTypes)[number]
const labels: Record<StudyType, string> = { radiography: 'Radiografía', radiography_2d: 'Radiografía 2D', cbct: 'CBCT', cephalometric_analysis: 'Análisis cefalométrico', study_models: 'Modelos de estudio', intraoral_scan: 'Escaneo intraoral', orthodontic_package: 'Paquete ortodóncico', aligner_package: 'Paquete de alineadores', laboratory_order: 'Orden de laboratorio', endodontic_evaluation: 'Evaluación endodóntica' }
const steps = ['Paciente', 'Clínica', 'Estudio', 'Detalles', 'Revisión', 'Confirmación']

export default function ProfessionalOrderWizard({ onBack }: { onBack: () => void }) {
  const router = useRouter(); const [step, setStep] = useState(1); const [access, setAccess] = useState<{ authenticated: boolean; active: boolean; doctor?: { firstName: string; paternalLastName: string; email: string } } | null>(null); const [clinics, setClinics] = useState<Clinic[]>([]); const [clinicId, setClinicId] = useState(''); const [studyType, setStudyType] = useState<StudyType>('radiography'); const [details, setDetails] = useState(defaultStudyDetails('radiography')); const [patient, setPatient] = useState({ firstName: '', paternalLastName: '', maternalLastName: '', birthDate: '', sex: 'unspecified' as 'male' | 'female' | 'other' | 'unspecified', phone: '', email: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState<{ folio: string } | null>(null)
  useEffect(() => { void getProfessionalOrderAccessAction().then(setAccess).catch(() => setAccess({ authenticated: false, active: false })); void getPublicClinicsAction().then((items) => { setClinics(items); setClinicId(items[0]?.id ?? '') }) }, [])
  const chooseType = (type: StudyType) => { setStudyType(type); setDetails(defaultStudyDetails(type)) }
  const valid = () => { if (step === 1 && !patient.firstName.trim()) return 'El nombre del paciente es obligatorio.'; if (step === 2 && !clinicId) return 'Selecciona una clínica.'; if (step === 4 && !studyDetailsSchemaByType[studyType].safeParse(details).success) return 'Completa los detalles requeridos.'; return '' }
  const next = () => { const message = valid(); setError(message); if (!message) setStep((current) => current + 1) }
  const submit = async () => { const message = valid(); if (message) return setError(message); setSubmitting(true); setError(''); const result = await createProfessionalOrderAction({ type: studyType, patient, clinicId, details }); setSubmitting(false); if (result.success) { setSuccess({ folio: result.data.folio }); setStep(6) } else setError('No fue posible crear la solicitud.') }
  if (!access) return <div className="py-16 text-center">Verificando acceso profesional...</div>
  if (!access.authenticated || !access.active || !access.doctor) return <Card className="mx-auto mt-16 max-w-xl"><CardHeader><CardTitle>Se requiere un perfil profesional activo</CardTitle><CardDescription>Inicia sesión y vincula tu perfil profesional.</CardDescription></CardHeader><CardContent><Button onClick={() => router.push('/login?redirect=%2Fappointments%3Ftipo%3Ddoctor')}>Continuar</Button></CardContent></Card>
  if (success) return <AppointmentWizardFrame title="Solicitud de estudios clínicos" subtitle="Tu solicitud quedó registrada." steps={steps} currentStep={6} backLabel="Elegir otra opción" onBack={onBack}><Card><CardContent className="space-y-3 pt-6"><CardTitle>Solicitud enviada</CardTitle><p>Folio: <strong>{success.folio}</strong></p><Button onClick={() => window.location.reload()}>Solicitar otro estudio</Button></CardContent></Card></AppointmentWizardFrame>
  return <AppointmentWizardFrame title="Solicitud de estudios clínicos" subtitle="Completa los datos para enviar la solicitud." steps={steps} currentStep={step} backLabel="Elegir otra opción" onBack={step > 1 ? () => setStep((current) => current - 1) : onBack}><Card><CardHeader><CardTitle>{steps[step - 1]}</CardTitle></CardHeader><CardContent className="space-y-4">{step === 1 && <div className="grid gap-3 sm:grid-cols-2"><label><span>Nombre *</span><Input required value={patient.firstName} onChange={(event) => setPatient({ ...patient, firstName: event.target.value })} /></label><label><span>Apellido paterno</span><Input value={patient.paternalLastName} onChange={(event) => setPatient({ ...patient, paternalLastName: event.target.value })} /></label><label><span>Apellido materno</span><Input value={patient.maternalLastName} onChange={(event) => setPatient({ ...patient, maternalLastName: event.target.value })} /></label><label><span>Fecha de nacimiento</span><Input type="date" value={patient.birthDate} onChange={(event) => setPatient({ ...patient, birthDate: event.target.value })} /></label><label><span>Teléfono</span><Input value={patient.phone} onChange={(event) => setPatient({ ...patient, phone: event.target.value })} /></label><label><span>Correo</span><Input type="email" value={patient.email} onChange={(event) => setPatient({ ...patient, email: event.target.value })} /></label></div>}{step === 2 && <NativeSelect value={clinicId} onChange={(event) => setClinicId(event.target.value)}>{clinics.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.name}</option>)}</NativeSelect>}{step === 3 && <fieldset className="grid gap-2 sm:grid-cols-2">{orderStudyTypes.map((type) => <Label key={type} className="rounded border p-3"><input type="radio" checked={studyType === type} onChange={() => chooseType(type)} /> {labels[type]}</Label>)}</fieldset>}{step === 4 && <StudyDetailsForm type={studyType} value={details} onChange={setDetails} />}{step === 5 && <div className="space-y-2 text-sm"><p><strong>Profesional:</strong> {access.doctor.firstName} {access.doctor.paternalLastName}</p><p><strong>Paciente:</strong> {patient.firstName} {patient.paternalLastName}</p><p><strong>Clínica:</strong> {clinics.find((clinic) => clinic.id === clinicId)?.name}</p><p><strong>Estudio:</strong> {labels[studyType]}</p></div>}{error && <p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2 border-t pt-4">{step < 5 ? <Button type="button" onClick={next}>Siguiente</Button> : <Button type="button" disabled={submitting} onClick={() => void submit()}>{submitting ? 'Enviando...' : 'Enviar solicitud'}</Button>}</div></CardContent></Card></AppointmentWizardFrame>
}
