/* eslint-disable @typescript-eslint/no-explicit-any */
import { and, asc, eq, gte, inArray, isNull, lt, or, sql } from 'drizzle-orm'
import { db } from '#/infrastructure/database'
import { member } from '#/infrastructure/auth/db/schema'
import { clinic } from '#/modules/clinic/db/schema'
import { order, orderEvent } from '#/modules/order/db/schema'
import { patient, patientHistory } from '#/modules/patient/db/schema'
import { appointment, appointmentEvent, appointmentReservation, calendarResource, resourceAvailability, resourceBlock } from '../db/schema'

const terminal = ['completed', 'cancelled', 'rejected', 'no_show'] as const
const inactiveReservationStatus = ['completed', 'cancelled', 'rejected', 'no_show'] as const
export const SLOT_NOT_AVAILABLE = 'SLOT_NOT_AVAILABLE'
type SlotInput = { clinicId: string; startsAt: Date; endsAt: Date; resourceIds: string[] }

function parts(date: Date, timezone: string) {
  const values = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23', weekday: 'short' }).formatToParts(date)
  return Object.fromEntries(values.filter((p) => p.type !== 'literal').map((p) => [p.type, p.value])) as Record<string, string>
}
function overlaps(a: Date, b: Date, c: Date, d: Date) { return a < d && c < b }
function localDay(date: Date, timezone: string) { const p = parts(date, timezone); return `${p.year}-${p.month}-${p.day}` }
function weekday(date: Date, timezone: string) { return ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(parts(date, timezone).weekday) }
function aligned(date: Date, timezone: string, interval: number) { return Number(parts(date, timezone).minute) % interval === 0 && date.getSeconds() === 0 && date.getMilliseconds() === 0 }

async function verifiedResources(tx: any, organizationId: string, slot: SlotInput) {
  const resources = await tx.select().from(calendarResource).where(and(eq(calendarResource.organizationId, organizationId), eq(calendarResource.clinicId, slot.clinicId), eq(calendarResource.status, 'active'), inArray(calendarResource.id, slot.resourceIds)))
  if (resources.length !== new Set(slot.resourceIds).size) throw new Error(SLOT_NOT_AVAILABLE)
  return resources
}
async function slotIsAvailable(tx: any, organizationId: string, slot: SlotInput, excludeAppointmentId?: string) {
  const [currentClinic] = await tx.select().from(clinic).where(and(eq(clinic.id, slot.clinicId), eq(clinic.organizationId, organizationId)))
  if (!currentClinic || slot.startsAt >= slot.endsAt || !aligned(slot.startsAt, currentClinic.timezone, currentClinic.slotIntervalMinutes) || !aligned(slot.endsAt, currentClinic.timezone, currentClinic.slotIntervalMinutes)) throw new Error(SLOT_NOT_AVAILABLE)
  await tx.execute(sql`SELECT id FROM calendar_resource WHERE id IN ${slot.resourceIds} FOR UPDATE`)
  await verifiedResources(tx, organizationId, slot)
  const availability = await tx.select().from(resourceAvailability).where(inArray(resourceAvailability.resourceId, slot.resourceIds))
  const day = weekday(slot.startsAt, currentClinic.timezone)
  for (const id of slot.resourceIds) {
    const range = availability.filter((v: any) => v.resourceId === id && v.dayOfWeek === day)
    const start = parts(slot.startsAt, currentClinic.timezone).hour + ':' + parts(slot.startsAt, currentClinic.timezone).minute
    const end = parts(slot.endsAt, currentClinic.timezone).hour + ':' + parts(slot.endsAt, currentClinic.timezone).minute
    if (!range.some((v: any) => v.startTime <= start && v.endTime >= end)) throw new Error(SLOT_NOT_AVAILABLE)
  }
  const blocks = await tx.select().from(resourceBlock).where(and(inArray(resourceBlock.resourceId, slot.resourceIds), lt(resourceBlock.startsAt, slot.endsAt), gte(resourceBlock.endsAt, slot.startsAt)))
  if (blocks.some((b: any) => overlaps(b.startsAt, b.endsAt, slot.startsAt, slot.endsAt))) throw new Error(SLOT_NOT_AVAILABLE)
  const reservations = await tx.select().from(appointmentReservation).where(and(inArray(appointmentReservation.resourceId, slot.resourceIds), eq(appointmentReservation.active, true), lt(appointmentReservation.startsAt, slot.endsAt), gte(appointmentReservation.endsAt, slot.startsAt)))
  if (reservations.some((r: any) => r.appointmentId !== excludeAppointmentId && overlaps(r.startsAt, r.endsAt, slot.startsAt, slot.endsAt))) throw new Error(SLOT_NOT_AVAILABLE)
  return currentClinic
}

export async function getAvailableSlots(input: { clinicId: string; date: string; durationMinutes: number; requiredResourceIds: string[] }, organizationId: string) {
  if (input.durationMinutes <= 0) throw new Error('INVALID_DURATION')
  const [currentClinic] = await db.select().from(clinic).where(and(eq(clinic.id, input.clinicId), eq(clinic.organizationId, organizationId)))
  if (!currentClinic) throw new Error('CLINIC_NOT_FOUND')
  const start = new Date(`${input.date}T00:00:00Z`); const candidates: Date[] = []
  for (let ms = start.getTime() - 14 * 3600000; ms < start.getTime() + 38 * 3600000; ms += currentClinic.slotIntervalMinutes * 60000) { const candidate = new Date(ms); if (localDay(candidate, currentClinic.timezone) === input.date && aligned(candidate, currentClinic.timezone, currentClinic.slotIntervalMinutes)) candidates.push(candidate) }
  const result = [] as { startsAt: Date; endsAt: Date }[]
  for (const startsAt of candidates) { const endsAt = new Date(startsAt.getTime() + input.durationMinutes * 60000); if (localDay(endsAt, currentClinic.timezone) !== input.date) continue; try { await slotIsAvailable(db, organizationId, { clinicId: input.clinicId, startsAt, endsAt, resourceIds: input.requiredResourceIds }); result.push({ startsAt, endsAt }) } catch (error) { if (!(error instanceof Error) || error.message !== SLOT_NOT_AVAILABLE) throw error } }
  return result
}

async function createInTx(tx: any, organizationId: string, userId: string, data: SlotInput & { patientId: string; kind: 'clinical' | 'study'; source: 'internal' | 'whatsapp' | 'public_order'; notes?: string; status: 'requested' | 'scheduled'; orderId?: string | null }, event: 'created' | 'requested' | 'scheduled' = 'created') {
  await slotIsAvailable(tx, organizationId, data)
  const [currentPatient] = await tx.select().from(patient).where(and(eq(patient.id, data.patientId), eq(patient.organizationId, organizationId)))
  if (!currentPatient) throw new Error('PATIENT_NOT_FOUND')
  const [created] = await tx.insert(appointment).values({ organizationId, clinicId: data.clinicId, patientId: data.patientId, orderId: data.orderId ?? null, kind: data.kind, source: data.source, status: data.status, startsAt: data.startsAt, endsAt: data.endsAt, notes: data.notes, createdByUserId: userId }).returning()
  await tx.insert(appointmentReservation).values(data.resourceIds.map((resourceId) => ({ appointmentId: created.id, resourceId, startsAt: data.startsAt, endsAt: data.endsAt })))
  await tx.insert(appointmentEvent).values({ appointmentId: created.id, type: 'created', userId, metadata: {} })
  if (event !== 'created') await tx.insert(appointmentEvent).values({ appointmentId: created.id, type: event, userId, metadata: {} })
  return created
}
export function createClinicalAppointment(organizationId: string, userId: string, data: SlotInput & { patientId: string; notes?: string; status: 'requested' | 'scheduled' }) { return db.transaction((tx) => createInTx(tx, organizationId, userId, { ...data, kind: 'clinical', source: 'internal' }, data.status === 'requested' ? 'requested' : 'scheduled')) }
export async function rescheduleAppointment(organizationId: string, userId: string, id: string, data: SlotInput & { patientId: string; notes?: string; status: 'requested' | 'scheduled' }) { return db.transaction(async (tx) => { const [existing] = await tx.select().from(appointment).where(and(eq(appointment.id, id), eq(appointment.organizationId, organizationId))); if (!existing || terminal.includes(existing.status as any)) throw new Error(SLOT_NOT_AVAILABLE); await slotIsAvailable(tx, organizationId, data, id); const [currentPatient] = await tx.select().from(patient).where(and(eq(patient.id, data.patientId), eq(patient.organizationId, organizationId))); if (!currentPatient) throw new Error('PATIENT_NOT_FOUND'); await tx.update(appointmentReservation).set({ active: false }).where(eq(appointmentReservation.appointmentId, id)); await tx.insert(appointmentReservation).values(data.resourceIds.map((resourceId) => ({ appointmentId: id, resourceId, startsAt: data.startsAt, endsAt: data.endsAt }))); const [updated] = await tx.update(appointment).set({ ...data, startsAt: data.startsAt, endsAt: data.endsAt, updatedAt: new Date() }).where(eq(appointment.id, id)).returning(); await tx.insert(appointmentEvent).values({ appointmentId: id, type: 'rescheduled', userId, metadata: {} }); return updated }) }

export async function scheduleOrderAppointment(organizationId: string, userId: string, data: Omit<SlotInput, 'clinicId'> & { orderId: string }) { return db.transaction(async (tx) => { const [currentOrder] = await tx.select().from(order).where(and(eq(order.id, data.orderId), eq(order.organizationId, organizationId))); if (!currentOrder || currentOrder.status !== 'received') throw new Error('ORDER_NOT_ELIGIBLE'); const [history] = await tx.select().from(patientHistory).where(eq(patientHistory.id, currentOrder.patientHistoryId)); if (!history) throw new Error('ORDER_NOT_FOUND'); const created = await createInTx(tx, organizationId, userId, { ...data, clinicId: currentOrder.clinicId, patientId: history.patientId, kind: 'study', source: currentOrder.source === 'public' ? 'public_order' : 'internal', status: 'scheduled', orderId: currentOrder.id }, 'scheduled'); await tx.update(order).set({ status: 'scheduled', updatedAt: new Date() }).where(eq(order.id, currentOrder.id)); await tx.insert(orderEvent).values({ orderId: currentOrder.id, type: 'order.scheduled', userId, metadata: { appointmentId: created.id } }); return created }) }

export async function transitionAppointment(organizationId: string, userId: string, memberId: string, role: string, id: string, status: 'requested' | 'scheduled' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'rejected' | 'no_show') { return db.transaction(async (tx) => { const [current] = await tx.select().from(appointment).where(and(eq(appointment.id, id), eq(appointment.organizationId, organizationId))); if (!current) throw new Error('APPOINTMENT_NOT_FOUND'); if (role === 'dentist') { if (!['in_progress', 'completed'].includes(status)) throw new Error('FORBIDDEN'); const assigned = await tx.select().from(appointmentReservation).innerJoin(calendarResource, eq(appointmentReservation.resourceId, calendarResource.id)).where(and(eq(appointmentReservation.appointmentId, id), eq(calendarResource.type, 'dentist'), eq(calendarResource.memberId, memberId))); if (!assigned.length) throw new Error('FORBIDDEN') } else if (!['owner', 'assistant'].includes(role)) throw new Error('FORBIDDEN'); const [updated] = await tx.update(appointment).set({ status, cancelledAt: status === 'cancelled' ? new Date() : current.cancelledAt, updatedAt: new Date() }).where(eq(appointment.id, id)).returning(); if (inactiveReservationStatus.includes(status as any)) await tx.update(appointmentReservation).set({ active: false }).where(eq(appointmentReservation.appointmentId, id)); await tx.insert(appointmentEvent).values({ appointmentId: id, type: status === 'in_progress' ? 'started' : status, userId, metadata: {} }); if (current.orderId && status === 'in_progress') { await tx.update(order).set({ status: 'in_progress', updatedAt: new Date() }).where(and(eq(order.id, current.orderId), eq(order.status, 'scheduled'))); await tx.insert(orderEvent).values({ orderId: current.orderId, type: 'order.started', userId, metadata: { appointmentId: id } }) } if (current.orderId && status === 'cancelled') { await tx.update(order).set({ status: 'received', updatedAt: new Date() }).where(and(eq(order.id, current.orderId), or(eq(order.status, 'scheduled'), eq(order.status, 'in_progress')))) } return updated }) }

export async function appointmentAccess(organizationId: string, userId: string) { const [current] = await db.select().from(member).where(and(eq(member.organizationId, organizationId), eq(member.userId, userId))); if (!current) throw new Error('FORBIDDEN'); return current }
export async function listAgenda(organizationId: string, userId: string, clinicId?: string, date?: string) {
  const access = await appointmentAccess(organizationId, userId)
  const agendaClinics = date ? await db.select({ id: clinic.id, timezone: clinic.timezone }).from(clinic).where(and(eq(clinic.organizationId, organizationId), clinicId ? eq(clinic.id, clinicId) : undefined)) : []
  if (date && !agendaClinics.length) return []
  const localDay = date ? or(...agendaClinics.map((currentClinic) => and(eq(appointment.clinicId, currentClinic.id), gte(appointment.startsAt, sql`(${date}::date::timestamp AT TIME ZONE ${currentClinic.timezone})`), lt(appointment.startsAt, sql`((${date}::date + 1)::timestamp AT TIME ZONE ${currentClinic.timezone})`)))) : undefined
  const rows = await db.select().from(appointment).where(and(eq(appointment.organizationId, organizationId), clinicId ? eq(appointment.clinicId, clinicId) : undefined, localDay)).orderBy(asc(appointment.startsAt))
  if (access.role !== 'dentist') { if (!['owner', 'assistant'].includes(access.role)) throw new Error('FORBIDDEN'); return rows }
  const reserved = await db.select().from(appointmentReservation).innerJoin(calendarResource, eq(appointmentReservation.resourceId, calendarResource.id)).where(and(eq(calendarResource.memberId, access.id), eq(calendarResource.type, 'dentist')))
  const ids = new Set(reserved.map((r: any) => r.appointment_reservation.appointmentId)); return rows.filter((row) => ids.has(row.id))
}

async function verifyResourceLinks(tx: any, organizationId: string, input: { clinicId: string; memberId?: string | null }) {
  const [currentClinic] = await tx.select().from(clinic).where(and(eq(clinic.id, input.clinicId), eq(clinic.organizationId, organizationId)))
  if (!currentClinic) throw new Error('CLINIC_NOT_FOUND')
  if (input.memberId) {
    const [currentMember] = await tx.select().from(member).where(and(eq(member.id, input.memberId), eq(member.organizationId, organizationId)))
    if (!currentMember) throw new Error('MEMBER_NOT_FOUND')
  }
}
export async function listPatients(organizationId: string) { return db.select({ id: patient.id, firstName: patient.firstName, paternalLastName: patient.paternalLastName, maternalLastName: patient.maternalLastName }).from(patient).where(eq(patient.organizationId, organizationId)).orderBy(asc(patient.firstName), asc(patient.paternalLastName), asc(patient.maternalLastName)) }
export async function listResources(organizationId: string, clinicId: string, activeOnly = false) { return db.select().from(calendarResource).where(and(eq(calendarResource.organizationId, organizationId), eq(calendarResource.clinicId, clinicId), activeOnly ? eq(calendarResource.status, 'active') : undefined)).orderBy(asc(calendarResource.name)) }
export async function createResource(organizationId: string, input: any) { return db.transaction(async (tx) => { await verifyResourceLinks(tx, organizationId, input); if (input.isPublicBookingDefault && input.status === 'active') await tx.update(calendarResource).set({ isPublicBookingDefault: false, updatedAt: new Date() }).where(and(eq(calendarResource.organizationId, organizationId), eq(calendarResource.clinicId, input.clinicId), eq(calendarResource.isPublicBookingDefault, true))); const [created] = await tx.insert(calendarResource).values({ ...input, organizationId }).returning(); return created }) }
export async function updateResource(organizationId: string, id: string, input: any) { return db.transaction(async (tx) => { await verifyResourceLinks(tx, organizationId, input); if (input.isPublicBookingDefault && input.status === 'active') await tx.update(calendarResource).set({ isPublicBookingDefault: false, updatedAt: new Date() }).where(and(eq(calendarResource.organizationId, organizationId), eq(calendarResource.clinicId, input.clinicId), eq(calendarResource.isPublicBookingDefault, true))); const [updated] = await tx.update(calendarResource).set({ ...input, updatedAt: new Date() }).where(and(eq(calendarResource.id, id), eq(calendarResource.organizationId, organizationId))).returning(); return updated }) }
export async function replaceResourceAvailability(organizationId: string, resourceId: string, values: any[]) { const resources = await db.select().from(calendarResource).where(and(eq(calendarResource.id, resourceId), eq(calendarResource.organizationId, organizationId))); if (!resources.length) throw new Error('RESOURCE_NOT_FOUND'); return db.transaction(async (tx) => { await tx.delete(resourceAvailability).where(eq(resourceAvailability.resourceId, resourceId)); if (values.length) await tx.insert(resourceAvailability).values(values.map((value) => ({ ...value, resourceId }))) }) }
export async function createResourceBlock(organizationId: string, input: any) { const resources = await db.select().from(calendarResource).where(and(eq(calendarResource.id, input.resourceId), eq(calendarResource.organizationId, organizationId))); if (!resources.length) throw new Error('RESOURCE_NOT_FOUND'); const [created] = await db.insert(resourceBlock).values(input).returning(); return created }

export async function listPublicClinics() { return db.select({ publicSlug: clinic.publicSlug, name: clinic.name, addressLine: clinic.addressLine, phone: clinic.phone }).from(clinic).where(and(eq(clinic.status, 'active'), isNull(clinic.archivedAt))).orderBy(asc(clinic.name)) }

async function publicClinic(tx: any, publicSlug: string) { const [current] = await tx.select().from(clinic).where(and(eq(clinic.publicSlug, publicSlug), eq(clinic.status, 'active'), isNull(clinic.archivedAt))); if (!current) throw new Error('BOOKING_UNAVAILABLE'); return current }
async function publicResource(tx: any, currentClinic: any) { const [resource] = await tx.select().from(calendarResource).where(and(eq(calendarResource.clinicId, currentClinic.id), eq(calendarResource.organizationId, currentClinic.organizationId), eq(calendarResource.status, 'active'), eq(calendarResource.isPublicBookingDefault, true))); if (!resource) throw new Error('BOOKING_UNAVAILABLE'); return resource }
function publicRange(date: string, timezone: string, interval: number) { const start = new Date(`${date}T00:00:00Z`); return Array.from({ length: Math.ceil((52 * 60) / interval) }, (_, index) => new Date(start.getTime() - 14 * 3600000 + index * interval * 60000)).filter((value) => localDay(value, timezone) === date) }

export async function getPublicAvailableSlots(input: { clinicPublicSlug: string; date: string }) { const currentClinic = await publicClinic(db, input.clinicPublicSlug); const resource = await publicResource(db, currentClinic); const now = new Date(); const latest = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000); const result: { startsAt: Date; endsAt: Date }[] = []; for (const startsAt of publicRange(input.date, currentClinic.timezone, currentClinic.slotIntervalMinutes)) { const endsAt = new Date(startsAt.getTime() + 30 * 60 * 1000); if (startsAt <= now || startsAt > latest || localDay(endsAt, currentClinic.timezone) !== input.date) continue; try { await slotIsAvailable(db, currentClinic.organizationId, { clinicId: currentClinic.id, startsAt, endsAt, resourceIds: [resource.id] }); result.push({ startsAt, endsAt }) } catch (error) { if (!(error instanceof Error) || ![SLOT_NOT_AVAILABLE, 'BOOKING_UNAVAILABLE'].includes(error.message)) throw error } } return result }

function normalizedPhone(value?: string) { const normalized = value?.replace(/\D/g, ''); return normalized || null }
export async function createPublicAppointment(input: { clinicPublicSlug: string; startsAt: Date; firstName: string; paternalLastName?: string; maternalLastName?: string; phone?: string; email?: string }) { try { return await db.transaction(async (tx) => { const currentClinic = await publicClinic(tx, input.clinicPublicSlug); const resource = await publicResource(tx, currentClinic); const endsAt = new Date(input.startsAt.getTime() + 30 * 60 * 1000); const now = new Date(); const latest = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000); if (input.startsAt <= now || input.startsAt > latest) throw new Error(SLOT_NOT_AVAILABLE); await slotIsAvailable(tx, currentClinic.organizationId, { clinicId: currentClinic.id, startsAt: input.startsAt, endsAt, resourceIds: [resource.id] }); if ((await publicResource(tx, currentClinic)).id !== resource.id) throw new Error(SLOT_NOT_AVAILABLE); const email = input.email?.trim().toLowerCase() || null; const phone = normalizedPhone(input.phone); const contact = or(email ? sql`lower(${patient.email}) = ${email}` : undefined, phone ? sql`regexp_replace(${patient.phone}, '[^0-9]', '', 'g') = ${phone}` : undefined); const [existing] = await tx.select().from(patient).where(and(eq(patient.organizationId, currentClinic.organizationId), contact)); const patientRecord = existing ?? (await tx.insert(patient).values({ organizationId: currentClinic.organizationId, firstName: input.firstName.trim(), paternalLastName: input.paternalLastName?.trim() || null, maternalLastName: input.maternalLastName?.trim() || null, email, phone }).returning())[0]; const duplicate = await tx.select({ id: appointment.id }).from(appointment).where(and(eq(appointment.organizationId, currentClinic.organizationId), eq(appointment.clinicId, currentClinic.id), eq(appointment.patientId, patientRecord.id), eq(appointment.startsAt, input.startsAt), sql`${appointment.status} not in ('completed', 'cancelled', 'rejected', 'no_show')`)); if (duplicate.length) throw new Error(SLOT_NOT_AVAILABLE); const [created] = await tx.insert(appointment).values({ organizationId: currentClinic.organizationId, clinicId: currentClinic.id, patientId: patientRecord.id, kind: 'clinical', source: 'public_order', status: 'scheduled', startsAt: input.startsAt, endsAt, createdByUserId: null }).returning(); await tx.insert(appointmentReservation).values({ appointmentId: created.id, resourceId: resource.id, startsAt: input.startsAt, endsAt }); await tx.insert(appointmentEvent).values({ appointmentId: created.id, type: 'scheduled', userId: null, metadata: { source: 'public_booking' } }); return { success: true as const } }) } catch (error) { if (error instanceof Error && error.message === SLOT_NOT_AVAILABLE) return { success: false as const, error: SLOT_NOT_AVAILABLE }; return { success: false as const, error: 'BOOKING_UNAVAILABLE' as const } } }
